apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-publisher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-publisher
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-publisher
subjects:
- kind: ServiceAccount
  name: event-publisher
  namespace: default
- kind: ServiceAccount
  name: event-publisher
  namespace: automated
roleRef:
  kind: ClusterRole
  name: event-publisher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-publisher-pvc
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-publisher
spec:
  selector:
    matchLabels:
      app: event-publisher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: event-publisher
    spec:
      serviceAccountName: event-publisher
      containers:
      - image: gcr.io/xl-ml-test/event-publisher:stable
        imagePullPolicy: Always
        name: event-publisher
        args:
        - --save_dir=/workspace/
        - --namespace=automated
        - --pubsub_topic=wcromar-test-topic
        - --model_output_bucket=$(OUTPUT_BUCKET)
        volumeMounts:
        - name: event-publisher-storage
          mountPath: /workspace/
        envFrom:
        - configMapRef:
            name: gcs-buckets
      volumes:
      - name: event-publisher-storage
        persistentVolumeClaim:
          claimName: event-publisher-pvc
