"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "tf-nightly-retinanet-convergence-v2-8"
  "namespace": "automated"
"spec":
  "concurrencyPolicy": "Forbid"
  "jobTemplate":
    "spec":
      "activeDeadlineSeconds": 36000
      "backoffLimit": 2
      "template":
        "metadata":
          "annotations":
            "tf-version.cloud-tpus.google.com": "nightly-2.x"
        "spec":
          "containers":
          - "args":
            - "python3"
            - "official/vision/detection/main.py"
            - "--tpu=$(KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS)"
            - "--strategy_type=tpu"
            - "--params_override=\"architecture\":\n  \"use_bfloat16\": true\n\"eval\":\n  \"batch_size\": 8\n  \"eval_file_pattern\": \"gs://xl-ml-test-us-central1/data/coco/val*\"\n  \"val_json_file\": \"gs://xl-ml-test-us-central1/data/coco/instances_val2017.json\"\n\"predict\":\n  \"predict_batch_size\": 8\n\"retinanet_parser\":\n  \"use_bfloat16\": true\n\"train\":\n  \"batch_size\": 64\n  \"checkpoint\":\n    \"path\": \"gs://xl-ml-test-us-central1/data/pretrain/resnet50-checkpoint-2018-02-07\"\n    \"prefix\": \"resnet50/\"\n  \"total_steps\": 22500\n  \"train_file_pattern\": \"gs://xl-ml-test-us-central1/data/coco/train*\""
            - "--mode=train"
            - "--model_dir=$(MODEL_DIR)"
            "env":
            - "name": "POD_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.name"
            - "name": "POD_UID"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.uid"
            - "name": "POD_NAMESPACE"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.namespace"
            - "name": "JOB_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.labels['job-name']"
            - "name": "METRIC_COLLECTION_CONFIG"
              "value": "{\n \"default_aggregation_strategies\": [\n  \"final\"\n ],\n \"write_to_bigquery\": \"True\"\n}"
            - "name": "MODEL_DIR"
              "value": "gs://xl-ml-test-us-central1/k8s/retinanet/convergence/v2-8/$(JOB_NAME)"
            - "name": "REGRESSION_TEST_CONFIG"
              "value": "{\n \"metric_success_conditions\": {\n  \"total_wall_time\": {\n   \"comparison\": \"less\",\n   \"success_threshold\": {\n    \"stddevs_from_mean\": 5\n   },\n   \"wait_for_n_points_of_history\": 10\n  }\n },\n \"write_to_error_reporting\": \"True\"\n}"
            - "name": "TEST_NAME"
              "value": "tf-nightly-retinanet-convergence-v2-8"
            "image": "gcr.io/xl-ml-test/model-garden:nightly"
            "imagePullPolicy": "Always"
            "name": "train"
            "resources":
              "limits":
                "cloud-tpus.google.com/v2": 8
          "restartPolicy": "Never"
  "schedule": "30 7 * * */2"