# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "tf-nightly-bert-mnli-convergence-v2-8"
  "namespace": "automated"
"spec":
  "concurrencyPolicy": "Forbid"
  "jobTemplate":
    "spec":
      "activeDeadlineSeconds": 7200
      "backoffLimit": 2
      "template":
        "metadata":
          "annotations":
            "tf-version.cloud-tpus.google.com": "nightly-2.x"
        "spec":
          "containers":
          - "args":
            - "python3"
            - "official/nlp/bert/run_classifier.py"
            - "--tpu=$(KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS)"
            - "--steps_per_loop=1000"
            - "--input_meta_data_path=gs://cloud-tpu-checkpoints/bert/classification/mnli_meta_data"
            - "--train_data_path=gs://cloud-tpu-checkpoints/bert/classification/mnli_train.tf_record"
            - "--eval_data_path=gs://cloud-tpu-checkpoints/bert/classification/mnli_eval.tf_record"
            - "--bert_config_file=gs://cloud-tpu-checkpoints/bert/keras_bert/uncased_L-24_H-1024_A-16/bert_config.json"
            - "--init_checkpoint=gs://cloud-tpu-checkpoints/bert/keras_bert/uncased_L-24_H-1024_A-16/bert_model.ckpt"
            - "--learning_rate=3e-5"
            - "--distribution_strategy=tpu"
            - "--train_batch_size=32"
            - "--eval_batch_size=32"
            - "--num_train_epochs=3"
            - "--model_dir=$(MODEL_DIR)"
            "env":
            - "name": "POD_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.name"
            - "name": "POD_UID"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.uid"
            - "name": "POD_NAMESPACE"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.namespace"
            - "name": "JOB_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.labels['job-name']"
            - "name": "METRIC_CONFIG"
              "value": "{\n \"metric_collection_config\": {\n  \"default_aggregation_strategies\": [\n   \"final\"\n  ],\n  \"write_to_bigquery\": true\n },\n \"regression_test_config\": {\n  \"metric_success_conditions\": {\n   \"total_wall_time\": {\n    \"comparison\": \"less\",\n    \"success_threshold\": {\n     \"stddevs_from_mean\": 5\n    },\n    \"wait_for_n_points_of_history\": 10\n   }\n  },\n  \"write_to_error_reporting\": true\n },\n \"test_name\": \"tf-nightly-bert-mnli-convergence-v2-8\"\n}"
            - "name": "MODEL_DIR"
              "value": "gs://xl-ml-test-us-central1/k8s/bert-mnli/convergence/v2-8/$(JOB_NAME)"
            "image": "gcr.io/xl-ml-test/model-garden:nightly"
            "imagePullPolicy": "Always"
            "name": "train"
            "resources":
              "limits":
                "cloud-tpus.google.com/v2": 8
          "restartPolicy": "Never"
  "schedule": "30 7 * * */2"