# Build generated files and push them to the gen branch.
name: Build Generated Files

on:
  push:
    branches: [master]
  
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Branch to gen
      run: |
        git branch -f gen
  
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install JSonnet
      run: |
        go install github.com/google/go-jsonnet/cmd/jsonnet@latest
        go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Build JSonnet templates
      run: |
        scripts/gen-tests.sh
    
    - name: Git Commit/Push Changes
      run: |
        git add --force -N k8s/*/gen/*.yaml
        git add -N k8s/
        git commit -m "Automatically updated using GitHub Actions"
        git push -f origin gen

